FROM ruby:3.4.1

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

RUN apt-get update -qq \
&& apt-get install -y --no-install-recommends \
    curl gnupg build-essential libpq-dev vim \
&& curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
&& apt-get install -y nodejs \
&& npm install -g yarn@1.22.22 \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /myapp

RUN gem install bundler

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .